// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../packages/FParsec.1.0.2/lib/net40-client/FParsec.dll"
#r "../../packages/FParsec.1.0.2/lib/net40-client/FParsecCS.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/Lidgren.Network.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/MonoGame.Framework.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/MonoGame.Framework.Net.dll"
#r "../../packages/NUnit.3.0.1/lib/net45/nunit.framework.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.Direct2D1.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.Direct3D11.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.Direct3D9.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.DXGI.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.MediaFoundation.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.RawInput.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.XAudio2.dll"
#r "../../../../../../../../Program Files (x86)/MonoGame/v3.0/Assemblies/Windows/SharpDX.XInput.dll"
#r "System.Core.dll"
#r "System.Data.dll"
#r "System.Data.Linq.dll"
#r "System.dll"
#r "System.Drawing.dll"
#r "System.Numerics.dll"
#r "System.Xml.dll"
#r "System.Xml.Linq.dll"